apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: my-application-3
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: nodejs3
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: nodejs3
  namespace: jephilli
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_sclorg_nodejs-ex
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/sclorg/nodejs-ex.git
